set nocompatible      " Enable Vim mode (instead of vi emulation)

syntax on         " Enable syntax highlighting
filetype plugin indent on
colorscheme sublimemonokai

"let g:is_posix = 1              " Our /bin/sh is POSIX, not bash
set smartindent                 " Intelligent indentation matching
set autoread                    " Update the file if it's changed externally
set backspace=indent,eol,start  " Allow backspacing over anything
set belloff=all                 " Turn off bells
set display=truncate            " Show '@@@' when the last screen line overflows
set formatoptions+=j            " Delete comment char when joining lines
set history=100                 " Undo up to this many commands
set hlsearch                    " Highlight search results
set incsearch                   " Highlight search matches as you type them
set ruler                       " Show cursor position
set ttyfast                     " Redraw faster for smoother scrolling
set wildmenu                    " Show menu for tab completion in command mode
set ttyfast	                    " Speed up scrolling in tty
set number                      " Show line numbers
set tabstop=4                   " Tab width is 4 spaces
set softtabstop=4
set autoindent
set cindent
set shiftwidth=4                " Use tabs of width 4 for indentation
set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<     " Chars to represent whitespace chars
set updatetime=100
set rnu
set foldmethod=syntax
set foldlevel=99
set foldlevelstart=99

" ALE settings
let g:ale_linters = {'rust': ['analyzer']}
let g:ale_fixers = {'rust': ['rustfmt', 'trim_whitespace', 'remove_trailing_lines']}
set completeopt=menu,menuone,preview,noselect,noinsert
let g:ale_completion_enabled = 1

" Rust-vim settings
"let g:rust_fold = 1
let g:rustfmt_autosave = 1

