set nocompatible      " Enable Vim mode (instead of vi emulation)

"Comment the following 2 lines to remove dracula theme
packadd! dracula
colorscheme dracula

"Uncomment the following line to enable monokai theme
"colorscheme sublimemonokai

syntax on         " Enable syntax highlighting
filetype plugin indent on

"let g:is_posix = 1              " Our /bin/sh is POSIX, not bash
set smartindent                 " Intelligent indentation matching
set autoread                    " Update the file if it's changed externally
set backspace=indent,eol,start  " Allow backspacing over anything
set belloff=all                 " Turn off bells
set display=truncate            " Show '@@@' when the last screen line overflows
set formatoptions+=j            " Delete comment char when joining lines
set history=100                 " Undo up to this many commands
set hlsearch                    " Highlight search results
set incsearch                   " Highlight search matches as you type them
set ruler                       " Show cursor position
set ttyfast                     " Redraw faster for smoother scrolling
set wildmenu                    " Show menu for tab completion in command mode
set ttyfast	                    " Speed up scrolling in tty
set number                      " Show line numbers
set tabstop=4                   " Tab width is 4 spaces
"set softtabstop= 4             " Leave these two disabled if using tabs
"set expandtab                  
set autoindent
set cindent
"set shiftwidth=0                " Use tabs of width 4 for indentation
set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<     " Chars to represent whitespace chars
set updatetime=100
set rnu							" Enable relative line numbers
set foldmethod=syntax
set foldlevel=99
set foldlevelstart=99
startinsert						" Begin vim in insert mode

"==MAPPINGS==

"Enter insert mode with q
map q i

"remove search highlighting when enter is pressed
nmap <Enter> :noh<Enter>

" DEL key does not overwrite any registers
map <DEL> "_x					


" background color switching between modes
" 234 = grey 11 and 0 = black
if !(has('gui_running')) "If in TUI vim
	autocmd InsertEnter * highlight Normal ctermbg=234
	autocmd InsertLeave * highlight Normal ctermbg=0
endif

"The colorscheme in the Day script seems to only work in gvim so for now they are locked behind this 'gui_running' check
if(has('gui_running')) "If in gvim
		"Next two lines identical to those found in night.vim, but are
		"neccesary so the script doesn't need to be run for higlighting
		:autocmd InsertEnter * highlight Normal guibg=#282A36 "The default dracula background color
		:autocmd InsertLeave * highlight Normal guibg=#000000 "black		
		command Day source ~/.vim/day.vim
		command Night source ~/.vim/night.vim
endif

" ALE settings
let g:ale_linters = {'rust': ['analyzer']}
let g:ale_fixers = {'rust': ['rustfmt', 'trim_whitespace', 'remove_trailing_lines']}
set completeopt=menu,menuone,preview,noselect,noinsert
let g:ale_completion_enabled = 1

" Rust-vim settings
"let g:rust_fold = 1
let g:rustfmt_autosave = 1

